name: Deploy to Google Cloud Run - Reuse Workflow
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  workflow:
    #uses: aldower/dso-templates/.github/workflows/angular.yaml@main
    uses: julio2019vp/ec-maven-users-api-jvp/.github/workflows/dockerhubazuretemplate.yaml@main

    with:
      IMAGE_NAME: "mi-aplicacion-java"
      IMAGE_TAG: "latest"
      DOCKERFILE_PATH: "Dockerfile"
      ACR_REGISTRY: "registryjvp.azurecr.io"
    secrets: inherit